### ISSUE TITLE
Experiment not running online on Pavlovia

### ISSUE THREAD

**Issue by Kbs21** [neuropsychology/ComplexSpan#4]
Hey, I wanted to run your experiment online on Pavlovia but after starting it gives an error, Just after the clicking spacebar on the instructions page. Can you help me solve this, please?
**error statement:**
ReferenceError: stimuli_count is not defined

**Comment by zen-juen** [comment]
Hi @Kbs21 thanks for reaching out! Can you share with me your PsychoPy version? (Asking because there has been some version related incompatibilities as reported in #3)

**Comment by Kbs21** [comment]
yes sure, my Psychopy version is 2021.1.4

**Comment by zen-juen** [comment]
Did you make any changes to the experiment file that you downloaded on this repo? Seems like the initiation of `stimuli_count` was not properly done before the first phase (presentation of individual letters) started. Can you check if `stimuli_count` is set to 2 under "Begin Experiment" in the customized code component under the `show_letters` routine?

![image](https://user-images.githubusercontent.com/54053748/125924103-5c83996b-0d7b-47c2-b73d-5a05d3e41f99.png)

**Comment by Kbs21** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/83883060/126047621-4414d11c-5b45-4560-80ac-3ec78ad615a3.png)
Yes, it is set to 2. I did not make any change to this repo after downloading it.

**Comment by Kbs21** [comment]
Also I have one more issue, I am trying to run the source on R studio and it gives this error :
![error](https://user-images.githubusercontent.com/83883060/126047724-f3ec075a-01a5-4dc5-9155-6aee0e19e49a.PNG)
Can you please help me figure this out, there is no extra '<' in the code, the code is from your experiment description, the first step-" # Download the function used to preprocess the data " part.

**Comment by zen-juen** [comment]
Could you upgrade your PsychoPy version to the 2021.2.0 and let me know if this works? (It should since it's working on my local copy using the latest version)

Regarding the source code error, could you
1) set the working directory of your R script to the statistics folder of the repo ("../ComplexSpan/statistics")
and
2) try with source("preprocessing.R") and  source("processing.R")

**Comment by Kbs21** [comment]
Hey, thanks for the reply. It turns out that easystats ecosystem is currently undergoing a bit of restructuring, and this is the reason why I can't download the packages (I'll have to wait until easystats/effectsize#361 is merged).

For now, it is recommend that I download the needed packages from CRAN. Can you please help me with the required packages

**Comment by zen-juen** [comment]
Hi @Kbs21 the easystats package is needed only if you want to produce the figures using `make_figures.R` in this repo, but otherwise to run the preprocessing and processing scripts you can simply `install.packages(c("tidyverse", "dplyr"))` before running the code 😄

**Comment by Kbs21** [comment]
Hey, I am getting this error on using process_WM function can you help resolve this I tried resinstalling packages magrittr and dplyr but the session gets aborted or it does not help and gives the same error.

process_WM(path_to_csv)
Error in dplyr::mutate(data, Span_Simple = max(Simple_Task$Set_Size) -  : 
  could not find function "%>%"

**Comment by zen-juen** [comment]
if you have tidyverse installed already, could you run `library(tidyverse)` before running the source code?

**Comment by Kbs2103** [comment]
Thanks a lot for your help, it all worked :)
